/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AuctionState {
  'currentPlayerId' : [] | [bigint],
  'leadingTeamId' : [] | [bigint],
  'isActive' : boolean,
  'currentBid' : bigint,
}
export interface Dashboard {
  'remainingPlayers' : bigint,
  'totalSpent' : bigint,
  'mostExpensivePlayer' : [] | [Player],
  'soldPlayers' : bigint,
}
export type ExternalBlob = Uint8Array;
export interface Player {
  'id' : bigint,
  'status' : string,
  'soldTo' : [] | [bigint],
  'name' : string,
  'soldPrice' : [] | [bigint],
  'imageUrl' : string,
  'category' : string,
  'rating' : bigint,
  'basePrice' : bigint,
}
export interface PlayerWithTeam { 'player' : Player, 'team' : [] | [Team] }
export type Result = { 'ok' : null } |
  { 'err' : string };
export interface Team {
  'id' : bigint,
  'purseAmountLeft' : bigint,
  'teamIconPlayer' : string,
  'teamLogo' : [] | [ExternalBlob],
  'isTeamLocked' : boolean,
  'ownerName' : string,
  'name' : string,
  'purseAmountTotal' : bigint,
  'numberOfPlayers' : bigint,
}
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  'addPlayer' : ActorMethod<[string, string, bigint, string, bigint], Result>,
  'adminLogin' : ActorMethod<[string], boolean>,
  'deletePlayer' : ActorMethod<[bigint], Result>,
  'editTeamPurse' : ActorMethod<[bigint, bigint], Result>,
  'getAuctionState' : ActorMethod<[], AuctionState>,
  'getDashboard' : ActorMethod<[], Dashboard>,
  'getPlayerById' : ActorMethod<[bigint], [] | [Player]>,
  'getPlayers' : ActorMethod<[], Array<Player>>,
  'getPlayersByCategory' : ActorMethod<[string], Array<Player>>,
  'getRemainingPurse' : ActorMethod<[bigint], [] | [bigint]>,
  'getResults' : ActorMethod<[], Array<PlayerWithTeam>>,
  'getTeamById' : ActorMethod<[bigint], [] | [Team]>,
  'getTeams' : ActorMethod<[], Array<Team>>,
  'placeBid' : ActorMethod<[bigint], Result>,
  'resetAuction' : ActorMethod<[], undefined>,
  'selectPlayer' : ActorMethod<[bigint], Result>,
  'sellPlayer' : ActorMethod<[], Result>,
  'updatePlayer' : ActorMethod<
    [bigint, string, string, bigint, string, bigint],
    Result
  >,
  'updateTeam' : ActorMethod<[bigint, string, string, string], Result>,
  'uploadTeamLogo' : ActorMethod<[bigint, ExternalBlob], Result>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];